//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don
    {
        public string ma_hoa_don { get; set; }
        public Nullable<int> id_san_pham { get; set; }
        public string ma_khach_hang { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
        public Nullable<double> tong_tien { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> tinh_trang { get; set; }
    }
}
