//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khach_hang
    {
        public int ma_khach_hang { get; set; }
        public string ten_khach_hang { get; set; }
        public Nullable<byte> phai { get; set; }
        public string dia_chi { get; set; }
        public string dien_thoai { get; set; }
        public string email { get; set; }
        public string ghi_chu { get; set; }
        public string mat_khau { get; set; }
    }
}
