//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai_san_pham
    {
        public int ma_loai { get; set; }
        public string ten_loai { get; set; }
        public string mo_ta { get; set; }
        public string hinh { get; set; }
    }
}
